/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7c839b",
        "inverse-on-surface": "#f3f0f2",
        "secondary": "#505f76",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e4e2e4",
        "background": "#fcf8fa",
        "surface-container-high": "#eae7e9",
        "status-critical-text": "#B91C1C",
        "status-urgent-bg": "#FFEDD5",
        "on-surface": "#1b1b1d",
        "tertiary-fixed-dim": "#dec29a",
        "surface-dark": "#0F172A",
        "status-urgent-text": "#C2410C",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed": "#271901",
        "border-dark": "#334155",
        "surface": "#fcf8fa",
        "border-light": "#E2E8F0",
        "status-non-urgent-text": "#15803D",
        "surface-variant": "#e4e2e4",
        "surface-container": "#f0edef",
        "surface-tint": "#565e74",
        "surface-dim": "#dcd9db",
        "primary-fixed-dim": "#bec6e0",
        "inverse-surface": "#303032",
        "on-secondary-fixed": "#0b1c30",
        "secondary-fixed": "#d3e4fe",
        "on-error-container": "#93000a",
        "status-critical-bg": "#FEE2E2",
        "inverse-primary": "#bec6e0",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "surface-bright": "#fcf8fa",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#98805d",
        "on-secondary-container": "#54647a",
        "status-priority-bg": "#DBEAFE",
        "surface-container-low": "#f6f3f5",
        "status-non-urgent-bg": "#DCFCE7",
        "tertiary-container": "#271901",
        "surface-container-lowest": "#ffffff",
        "outline": "#76777d",
        "surface-light": "#F8FAFC",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "tertiary-fixed": "#fcdeb5",
        "secondary-container": "#d0e1fb",
        "status-priority-text": "#1D4ED8",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed-variant": "#574425",
        "on-background": "#1b1b1d",
        "primary-fixed": "#dae2fd",
        "primary-container": "#131b2e"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "element-gap": "0.75rem",
        "container-padding": "1.5rem",
        "stack-tight": "0.5rem",
        "grid-gutter": "1rem"
      },
      "fontFamily": {
        "logo": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "logo": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.05em", "fontWeight": "700" }],
        "data-tabular": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "label-caps": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.025em", "fontWeight": "600" }],
        "headline-md": ["1.125rem", { "lineHeight": "1.5rem", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
